# Makes  Python module 

# Rodrigo Caballero Augi (rca@geosci.uchicago.edu), 
# Department of the Geophysical Sciences, University of Chicago
# 2004

name := NumPtr

OS := $(shell uname -s)

include $(CLIMT_SRC_DIR)/CompilerFlags.mk
include $(CLIMT_SRC_DIR)/Rules.mk
